### ISSUE TITLE
Error while click on apoved holidays

### ISSUE THREAD

**Issue by zamach132** [InfotelGLPI/activity#10]
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/glpi/inc/html.class.php:1439) in /var/www/html/glpi/plugins/activity/front/cra.php on line 44

GLPI 9.5.1-git-9.4/bugfixes-8156d205fe (/glpi => /var/www/html/glpi)
Installation mode: GIT

[2020-10-15 15:46:17] glpiphplog.WARNING:   *** PHP Warning (2): Cannot modify header information - headers already sent by (output started at /var/www/html/glpi/inc/html.class.php:1439) in /var/www/html/glpi/plugins/activity/front/cra.php at line 44
  Backtrace :
  plugins/activity/front/cra.php:44                  header()

**Comment by gguib** [comment]
Try last version 3.0.1

**Comment by zamach132** [comment]
Where do You have this version ? Here I see only 3.0.0

**Comment by gguib** [comment]
on master branch.

**Comment by zamach132** [comment]
3.0.1 work well. Thanks a lot.
