### ISSUE TITLE
PHP Error (1): Cannot declare class PluginActivityActions, because the name is already in use in /var/www/html/g952/plugins/activity/inc/planningexternalevent.class.php at line 32

### ISSUE THREAD

**Issue by jcervantes-sipecom** [InfotelGLPI/activity#12]
I did an upgrade from GLPI 9.4.6 and plugin 2.5.0 to GLPI 9.5.2 and plugin 3.0.0

Plugin version: 3.0.0
Glpi version: 9.5.2
SO: Ubuntu

When trying to enable the plugin I got this error:

> PHP Error (1): Cannot declare class PluginActivityActions, because the name is already in use in /var/www/html/g952/plugins/activity/inc/planningexternalevent.class.php at line 32

And the plugin page got entirely blank:
![image](https://user-images.githubusercontent.com/56606032/96518170-ef26ea80-122f-11eb-83eb-44ebcc443ed7.png)

When comment the following lines:

> class PluginActivityActions {
   const ADD_ACTIVITY     = 'add_activity';
   const LIST_ACTIVITIES  = 'list_activities';
   const HOLIDAY_REQUEST  = 'holiday_request';
   const LIST_HOLIDAYS    = 'list_holidays';
   const APPROVE_HOLIDAYS = 'validate_holidays';
   const CRA              = 'cra';
   const HOLIDAY_COUNT    = 'holiday_count';
   const MANAGER          = 'manager';
}

I can access to the plugin page:
![image](https://user-images.githubusercontent.com/56606032/96518029-96575200-122f-11eb-893b-260c0434a364.png)

**Comment by gguib** [comment]
Hi, i retry on 9.4.6 to 9.5.2 and i have no error, class PluginActivityActions  is well implemented. Have you apache errors as well ?

**Comment by jcervantes-sipecom** [comment]
No, I don't have any log in php-errors just: 

> glpiphplog.ALERT:`   *** PHP Compile Error (64): Cannot declare class PluginActivityActions, because the name is already in use in /var/www/html/g952/plugins/activity/inc/planningexternalevent.class.php at line 32

I did:

> grep -R --exclude-dir=files "PluginActivityActions" .

And I found this class repeat twice:

> ./plugins/activity/inc/activity.class.php:class PluginActivityActions {
./plugins/activity/inc/planningexternalevent.class.php:class PluginActivityActions {

So I delete the folder Activity, and download again the last realease, I did again the previous command and I got just 1 line that has the class:

> ./plugins/activity/inc/planningexternalevent.class.php:class PluginActivityActions {

So that was the solution.
