### ISSUE TITLE
External event planed on public holidays

### ISSUE THREAD

**Issue by zamach132** [InfotelGLPI/activity#13]
When i plan externalevent which repeat it can be planned on public holidays. I know that i can use exceptions but when i'm planning events for multiple user it is just place for mistake. Is there any way to deny any event to be planned on public holiday with this plugin ?

![obraz](https://user-images.githubusercontent.com/62652551/97412083-5bc17980-1901-11eb-9162-3a2acc779ee7.png)
![obraz](https://user-images.githubusercontent.com/62652551/97412113-68de6880-1901-11eb-8f67-0c47526f2f40.png)

**Comment by gguib** [comment]
Hi, 

Can you please check new fix on master branch.

**Comment by zamach132** [comment]
It worked.
Exception adds automatically.

SOLVED


![obraz](https://user-images.githubusercontent.com/62652551/97837061-d1e92600-1cdd-11eb-8179-b9597b90440f.png)
