### ISSUE TITLE
Forms Creator is interfering with the Radio buttons of Activity plugin.

### ISSUE THREAD

**Issue by jcervantes-sipecom** [InfotelGLPI/activity#15]
Hi, I opened a issue in Form Creator, because it seems that being active it interferes with the interface of Activity and another plugin, making the Radio Buttons disappear, this is the open ISSUE: [formcreator/#2009](https://github.com/pluginsGLPI/formcreator/issues/2009)

Basically this happens:

**Screenshots**
- When Forms creator is **disabled:**
> - Activity:
![image](https://user-images.githubusercontent.com/56606032/99086502-9e3cb480-2597-11eb-8baf-4f8f2f736e0f.png)

**As you can see the radio buttons on the plugin is visible**

- But when Form Creator is **enabled:**
> - Activity:
![image](https://user-images.githubusercontent.com/56606032/99087005-40f53300-2598-11eb-9430-f23e39e9bac3.png)

**As you can see the radio buttons on the plugin is invisible or not displayed**

I don't know exactly what the problem would be so I inform the 2 plugins.

**Comment by gguib** [comment]
Hi, 

It seems to be fixed with new css applied on formcreator plugin ?

**Comment by jcervantes-sipecom** [comment]
Yes, exactly the patch on Forms, solved the problem with radio buttons.
