### ISSUE TITLE
Conflict with 'Ticket tasks' and 'Deploy tasks' in Planning

### ISSUE THREAD

**Issue by jcervantes-sipecom** [InfotelGLPI/activity#18]
Hello,

I cannot see in Planning the tasks that have been scheduled when the plugin is activated. And the reason is that I notice that the plugin deactivates, eliminates or makes these two options that come by default disappear: 'Ticket tasks' and 'Deploy tasks'. I show captures.

Without the plugin activated:

![image](https://user-images.githubusercontent.com/56606032/123841236-edd8b200-d8d4-11eb-8db9-a48915ecd956.png)

With the plugin activated:

![image](https://user-images.githubusercontent.com/56606032/123842057-f1b90400-d8d5-11eb-8f1e-c8a0b5465893.png)

Although this time it seems that 'Deploy tasks' does appear, it can be seen that 'Ticket tasks' has disappeared.

**Comment by tsmr** [comment]
https://github.com/InfotelGLPI/activity/issues/21
