### ISSUE TITLE
Missing "ASK holidays"

### ISSUE THREAD

**Issue by tomdas** [InfotelGLPI/activity#19]
Hello , 

I need help because i want try the plugin Activity but i don't understand why i a don't have the button "Ask holiday" ( demande de congés en francais).

![Capture](https://user-images.githubusercontent.com/85169402/133258697-5e940b1c-86a2-4bd2-a250-616e73a971e4.PNG)

If you have an idea ? 

Thanks a lot

Thomas

**Comment by tomdas** [comment]
Hello , 

Waouuu , thanks for your answer really fast.

**Hello do you have defined a responsible in your preferences ?** > no but when i try i clic to add but nothing is add

![plugin](https://user-images.githubusercontent.com/85169402/133262973-e5bc547c-73aa-4d6a-af54-648cb6db22b5.PNG)

thanks again.

Ps : si tu parle Français je suis preneur ^^

**Comment by tsmr** [comment]
Have you any errors in debug mode ?

PS : I'am french too but for english users - it's better :)

**Comment by tomdas** [comment]
ok.....

So i try with the admin glpi, and this work really fine.

But with user (technicien) i can't add.
![Capture2](https://user-images.githubusercontent.com/85169402/133266087-64349548-2cdc-4aff-ae90-61437190576c.PNG)

 may be a concern of right of access ?

Thanks

**Comment by tsmr** [comment]
Yes i think it's with create right

**Comment by tomdas** [comment]
Yes it's that.

Now i try this correctly.

Thanks a lot.

Merci pour vos retour plus que rapide ^^ > Thank you for your quick feedback
