### ISSUE TITLE
Cannot delete or update a parent row

### ISSUE THREAD

**Issue by Gwenaelle93** [InfotelGLPI/activity#2]
Can not delete a job in a ticket. here is the error in the log file : 

> [2019-11-14`` 15:47:08] glpisqllog.ERROR: DBmysql::query() in \root\inc\dbmysql.class.php line 188
>   *** MySQL query error:
>   SQL: DELETE `glpi_tickettasks` FROM `glpi_tickettasks` WHERE `id` = '13868'
>   Error: Cannot delete or update a parent row: a foreign key constraint fails (`glpi_db`.`glpi_plugin_activity_tickettasks`, CONSTRAINT `glpi_plugin_activity_tickettasks_ibfk_1` FOREIGN KEY (`tickettasks_id`) REFERENCES `glpi_tickettasks` (`id`))
>   Backtrace :
>   inc\dbmysql.class.php:1055                         
>   inc\commondbtm.class.php:723                       DBmysql->delete()
>   inc\commondbtm.class.php:1674                      CommonDBTM->deleteFromDB()
>   front\commonitiltask.form.php:67                   CommonDBTM->delete()
>   front\tickettask.form.php:36                       `include()

After uninstalling and reinstalling the plugin, the problem is gone

Plugin version : 2.5.0
GLPI version :  9.4.4
PHP 7.3.5
Server Version: 10.0.20-MariaDB

**Comment by M-Falken** [comment]
Same for me:
[2019-12-26 11:09:55] glpisqllog.ERROR: DBmysql::query() in /home/emaging/public_html/GLPINEW/inc/dbmysql.class.php line 188
```
  *** MySQL query error:
  SQL: UPDATE `glpi_plugin_activity_tickettasks` SET `tickettasks_id` = '0' WHERE `id` = '1019'
  Error: Cannot add or update a child row: a foreign key constraint fails (`xxxxxx_GLPI945`.`glpi_plugin_activity_tickettasks`, CONSTRAINT `glpi_plugin_activity_tickettasks_ibfk_1` FOREIGN KEY (`tickettasks_id`) REFERENCES `glpi_tickettasks` (`id`))
  Backtrace :
  inc/dbmysql.class.php:948                          
  inc/commondbtm.class.php:616                       DBmysql->update()
  inc/commondbtm.class.php:1441                      CommonDBTM->updateInDB()
  inc/commondbtm.class.php:814                       CommonDBTM->update()
  inc/commondbtm.class.php:718                       CommonDBTM->cleanRelationData()
  inc/commondbtm.class.php:1668                      CommonDBTM->deleteFromDB()
  front/commonitiltask.form.php:67                   CommonDBTM->delete()
  front/tickettask.form.php:36                       include()
  {"user":"6634@hybridxxxx.fr.ns.dummy.tld"} 
[2019-12-26 11:09:55] glpisqllog.ERROR: DBmysql::query() in /home/emaging/public_html/GLPINEW/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: DELETE `glpi_tickettasks` FROM `glpi_tickettasks` WHERE `id` = '18217'
  Error: Cannot delete or update a parent row: a foreign key constraint fails (`xxxxxx_GLPI945`.`glpi_plugin_activity_tickettasks`, CONSTRAINT `glpi_plugin_activity_tickettasks_ibfk_1` FOREIGN KEY (`tickettasks_id`) REFERENCES `glpi_tickettasks` (`id`))
  Backtrace :
  inc/dbmysql.class.php:1055                         
  inc/commondbtm.class.php:723                       DBmysql->delete()
  inc/commondbtm.class.php:1668                      CommonDBTM->deleteFromDB()
  front/commonitiltask.form.php:67                   CommonDBTM->delete()
  front/tickettask.form.php:36                       include()
  {"user":"6634@hybridxxxx.fr.ns.dummy.tld","mem_usage":"0.006\", 3.52Mio)"} 
```
But didn't try to reinstall yet

Plugin version : 2.5.0
GLPI version : 9.4.5
PHP 7.3.12
Server Version: 10.0.30-MariaDB

**Comment by gguib** [comment]
problem fixed.
