### ISSUE TITLE
Stuck in duration calculation when selecting more than one day of holiday

### ISSUE THREAD

**Issue by eandry77** [InfotelGLPI/activity#20]
When the holiday range is more than one day, the duration calculation is stuck:

![duration](https://user-images.githubusercontent.com/6266436/142721885-7c883180-1ed3-4e33-999b-77d00be0fe5a.png)
.

I'm using latest version of the plugin on GLPI 9.5.6.
Also tried the github snapshot 9.5/bugfixes with same result.

**Comment by jmichault** [comment]
même chose pour moi.
Précision : lors de l'appel de duration.php, on obtient la réponse : 
`L'action que vous avez réalisée n'est pas autorisée.
[GLPI Copyright (C) 2015-2022 Teclib' and contributors](http://glpi-project.org/)`

**Comment by eandry77** [comment]
Sorry, but I still have the issue with this fix, duration is still stuck calculating.

**Comment by tsmr** [comment]
Have you clean your cache after modification ?

**Comment by eandry77** [comment]
I didn't.
I works now, sorry for the noise.

Thanks a lot !
