### ISSUE TITLE
Problème d'association de responsable

### ISSUE THREAD

**Issue by ShrekR** [InfotelGLPI/activity#24]
Bonjour,

J'ai plusieurs utilisateurs qui appartiennent à plusieurs groupes, certains de ses groupes ont des responsables et d'autres non.
Lorsque j'active l'option :"Utiliser les superviseurs des groupes comme responsables des congés",  les utilisateurs se rendent ensuite dans "mes préférences" et je n'ai aucun responsable qui remonte.
J'ai fait des test avec un utilisateur appartenant à un seul groupe (avec responsable) et ça fonctionne.
Dans la liste des groupes de mes utilisateurs, il n'y a de responsables ni sur le premier, ni sur le dernier des groupes.
J'ai regarder le code source, je connais pas grand chose en php, mais je pense que le soucis pourrais être entre les lignes 102 et 111 du fichier "preference.class.php".
         `$groupusers` = Group_User::getUserGroups($user_id);
         $groups = [];
         foreach ($groupusers as $groupuser) {
            $groups[] = $groupuser["id"];
         }
         $dbu = new DbUtils();
         $restrict = ["groups_id" => [implode(',', $groups)],
                     "is_manager" => 1,
                      "NOT" => ["users_id"  => $user_id]];
         $managers = $dbu->getAllDataFromTable('glpi_groups_users', $restrict);`

En espérant vous lire bientôt,

Bonne journée.

**Comment by tsmr** [comment]
Bonjour
Pourriez-vous me donner la version de GLPI et du plugin ? merci

**Comment by ShrekR** [comment]
Bonjour,

 

J’utilise GLPI en 10.0.1 et Activity en 3.1.1

 

Merci

 

 

Cordialement / Best regards

 

Kevin REYNEAU

Responsable Informatique

METAL-CHROME

Tél : 05.46.82.28.28 - Mob : 06.14.47.95.59

 <https://antiphishing.vadesecure.com/2/a2V2aW4ucmV5bmVhdUBtZXRhbC1jaHJvbWUuY29tfFZSQzgxNDU4OA%3D%3D/antiphishing.vadesecure.com/2/c2V2ZXJpbmUuY29ydGVzQG1ldGFsLWNocm9tZS5jb218VlJDODE0NTg4/antiphishing.vadesecure.com/1/a2V2aW4ucmV5bmVhdUBtZXRhbC1jaHJvbWUuY29tfFZSQzgxNDU4OA%25253D%25253D/www.metal-chrome.com/> www.metal-chrome.com





 

De : Xavier CAILLAUD ***@***.***> 
Envoyé : jeudi 23 juin 2022 16:16
À : InfotelGLPI/activity ***@***.***>
Cc : Kevin Reyneau ***@***.***>; Author ***@***.***>
Objet : Re: [InfotelGLPI/activity] Problème d'association de responsable (Issue #24)

 

Bonjour
Pourriez-vous me donner la version de GLPI et du plugin ? merci
