### ISSUE TITLE
Compteur de congé

### ISSUE THREAD

**Issue by Bonbob** [InfotelGLPI/activity#4]
Bonjour,

Sur deux installations de GLPI en version 9.4.4 et 9.4.5, ainsi que du plugin Activity en version 2.5.0, nous avons constaté que le cumul des congés et le décompte ne sont pas actifs.

La prise en compte du compteur ne fonctionne pas.
Les congés sont bien listés dans le planning et via  l'icone dans la barre supérieure. Mais à aucun moment le décompte est pris en charge.

Merci par avance.

DG

**Comment by keha35** [comment]
Bonjour,

Vous pouvez voir le décompte au moment de poser un congé.
Nous avons constaté que le compteur ne s'affiche pas lorsque vous avez la possibilité de poser des congés pour les autres utilisateurs.
