### ISSUE TITLE
Holidays Counters is not showing the icon

### ISSUE THREAD

**Issue by jcervantes-sipecom** [InfotelGLPI/activity#5]
The seccion "Holiday counters" is not showing the icon, I tried to revise the code but I couldn't find why, just this option not show the icon, because I replace the code in the CSS to point another Font Awesome pic, but nothing, I tried the same with "List of holidays" and succesfully change it, so the link to Font Awesome is right.

![Selection_104](https://user-images.githubusercontent.com/56606032/76553586-4d057f80-6462-11ea-83bb-55698f03ca76.png)

**Comment by keha35** [comment]
Hi, 

Is the probleme still in progress ?
It can be a cache probleme 
Or it's because the font awsesome pic isn't compatible.

**Comment by jcervantes-sipecom** [comment]
Hi,

Answered you:
Is the probleme still in progress ?
- Yes, the problem is still present

It can be a cache probleme
- I tried in different browsers, in private/incognite browser mode and now in GLPI 9.4.6 version, but the problem persist

Or it's because the font awsesome pic isn't compatible.
- I don't know exactly if it is, but I don't think so because as I said I tried this: 

> replace the code in the CSS to point another Font Awesome pic, but nothing, I tried the same with "List of holidays" and succesfully change it, so the link to Font Awesome is right.

The plugin version is: 2.5.0

**Comment by gguib** [comment]
Hi Is the probleme still in progress ?
Have you some logs in your browser console ? js errors or something ?

**Comment by jcervantes-sipecom** [comment]
Hi, 
In mys test enviroment of the new version 3.0.0 for GLPI 9.5.2 this not happen, but it still happen in 1.3.1 for GLPI 9.4.6.

- 3.0.0
![image](https://user-images.githubusercontent.com/56606032/97313531-bb058800-1834-11eb-9414-bc8dc3ddf7cd.png)

- 1.3.1

![image](https://user-images.githubusercontent.com/56606032/97313551-c3f65980-1834-11eb-9b5e-c83a1cd0168f.png)

In console a got this:

![image](https://user-images.githubusercontent.com/56606032/97313802-09b32200-1835-11eb-9f9b-658b5800a4f4.png)

But I think this is not the problem.

**Comment by gguib** [comment]
1.3.1 for GLPI 9.4.6 ? have you tried with 2.5.0 version instead ?

**Comment by jcervantes-sipecom** [comment]
Sorry, my mistake I'm confused with the versión of other plugin, I actually have the 2.5.0 version:

![image](https://user-images.githubusercontent.com/56606032/97333303-6d474a80-1849-11eb-8e79-f32563b8cc71.png)

**Comment by jcervantes-sipecom** [comment]
Hi, this was solved upgrading the plugin version to 3.0.0, now I have glpi version 9.5.7.

![image](https://user-images.githubusercontent.com/56606032/155763175-57f67427-ef72-4be1-b29f-1957c0994a22.png)
