### ISSUE TITLE
plugin is not sending notification via mail. 

### ISSUE THREAD

**Issue by zamach132** [InfotelGLPI/activity#9]
Hi there, 
First of all thanks for very usefull plugin. You did great job. 
I'm using this plugin ver 3.0.0 with GLPI 9.5.1. 
Instalation method git. 

My problem is mail notification. When I push button says "SSend the mail for this holiday" , I've got response 
"Error in sending the email
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting"

GLPI notifications are working well. Also i dont see any information in mail log or mail error log so in my opinion it looks like ACTIVITY is using diferent mailer, is it ?Or maybe there is another log for ACTIVITY mail actions.

Please help me to resolve this issue. 

Greetings

**Comment by tsmr** [comment]
Hello

Have you any errors into glpi/files/_log ?

**Comment by zamach132** [comment]
After your mesage i've cheked one  more time logs files. That is all i found

[2020-09-21 16:50:57] glpiphplog.NOTICE: Toolbox::decrypt() in /var/www/html/glpi/inc/toolbox.class.php line 311
Use sodiumDecrypt  {"user":"32@debian"}

**Comment by zamach132** [comment]
Your question pushed me to put password directly in 

notificationmail.class.php

It worked. But i know it is not a solution.
